title: Michael Levy
email: example@example.com
description: Michael Levy's website
url: "https://example.org"
twitter: mlevy_

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed
